<?php 
// ==================================================================
//  Author: Robert Joseph (dart@vizmotion.com)
//	 Web: http://wiki.bssd.org/index.php/DART_System
// ==================================================================
?>
<div align="center">
	<table width="100%" border="0" cellspacing="2" cellpadding="0">
		<tr>
			<td colspan="3">
				
			</td>
		</tr>
		<tr>
			<td nowrap width="33%"><a title="DART Project Information" href="http://wiki.bssd.org/index.php/DART_System" target="_blank">DART Project Info</a> :: <a title="DART Support Information" href="http://wiki.bssd.org/index.php/DART_System#DART_Technical_Support">Support</a> :: <a title="DART Contact Information" href="http://wiki.bssd.org/index.php/DART_System#DART_Contacts" target="_blank">Contact</a></td>
			<td valign="middle" nowrap width="30%">
				<div align="center">
					<a title="This software is licensed under the CC-GNU GPL." href="http://creativecommons.org/licenses/GPL/2.0/" target="_blank"><img src="<?php echo  $imageURL ?>somerights20.gif" alt="Attribution-NonCommercial-ShareAlike 2.5 License" height="31" width="88" align="absmiddle" border="0"></a></div>
			</td>
			<td valign="middle" nowrap width="60%">
				<div align="right">
					DART: Standards tracking that is free like a puppy!</div>
			</td>
		</tr>
	</table>
</div>
