<div align="center">
	<table width="100%" border="0" cellspacing="2" cellpadding="0">
		<tr>
			<td colspan="3">
				
			</td>
		</tr>
		<tr>
			<td nowrap width="33%"><a title="DART Project Information" href="http://wiki.bssd.org/index.php/DART_System" target="_blank">DART Project Info</a> :: <a href="http://wiki.bssd.org/index.php/DART_System#DART_Technical_Support">Support</a> :: <a title="DART Contact Information" href="http://wiki.bssd.org/index.php/DART_System#DART_Contacts" target="_blank">Contact</a></td>
			<td valign="middle" nowrap width="30%">
				<div align="center">
					<a title="Creative Commons License" href="http://creativecommons.org/licenses/by-nc-sa/2.5/" target="_blank"><img src="http://dart.bssd.org/images/somerights20.gif" alt="Attribution-NonCommercial-ShareAlike 2.5 License" height="31" width="88" align="absmiddle" border="0"></a></div>
			</td>
			<td valign="middle" nowrap width="60%">
				<div align="right">
					DART: Standards tracking that is free like a puppy!</div>
			</td>
		</tr>
	</table>
</div>
