<?php
// ==================================================================
//  Author: Robert Joseph (dart@vizmotion.com)
//	 Web: http://wiki.bssd.org/index.php/DART_System
// ==================================================================
?>

<a name='top_anchor'>
    <img src="<?php echo $imageURL ?>frontlogo.gif" alt="" />
</a>
<a href="http://wiki.bssd.org/index.php/DART_System" target="_blank">
    DART Project Info</a> ::
<a title="DART Support Information"
   href="http://wiki.bssd.org/index.php/DART_System#DART_Technical_Support">
    Support</a> ::
<a title="DART Contact Information"
   href="http://wiki.bssd.org/index.php/DART_System#DART_Contacts"
   target="_blank">Contact
</a>
