<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html>

	<head>
		<meta http-equiv="content-type" content="text/html;charset=iso-8859-1">
		<meta name="generator" content="Adobe GoLive">
		<title>Current Progress Report</title>
		<link rel="stylesheet" href="css/dart.css" type="text/css">
	</head>

	<body bgcolor="#ffffff">
		<form>
		<input type=hidden name=id value="$id">
		<input type=hidden name="cmd" value="repcurrentcreate">
		Start: <input type=text name=start value="$start"> Finish: <input type=text name=finish value=$finish>
		<input type=submit name=submit value=Submit>
		</form>
		<table border="0" cellpadding="0" cellspacing="0" background="(EmptyReference!)">
			<tr>
				<td valign="top" width="100%">
					<div align="center">
						<table width="100%" border="0" cellspacing="2" cellpadding="0">
							<tr>
								<td>

									<div align="center">
										<table width="75%" border="1" cellspacing="2" cellpadding="0">
											<tr>
												<td width="25%">
													<div align="center">
														<img src="$img" alt="" border="0"></div>
												</td>
												<td nowrap width="50%">
													<div align="center">

														<font size="4" color="black">$sitename<br>
															$sname</font><font size="4"><br>
															<br>
														</font><b><font size="2">Attendance: </font></b><font size="2">Present $present <b>|</b> Absent $absent | Rate $rate% </font><b><font size="2"><br>
																AK Student ID: </font></b><font size="2">$alaskaid<br>

															<b>Date Generated:</b> $dategen</font><font size="4"></font></div>
												</td>
												<td nowrap width="25%">
													<div align="center">
														<img src="$picture" alt="$sname - $sitename" height="105" width="95" border="0"></div>
												</td>
											</tr>

											<tr>
												<td nowrap width="25%">
													<div align="center">
														<font size="2"><b>Enrolled: </b>$enrolled</font></div>
												</td>
												<td nowrap width="50%">
													<div align="center">
														<font size="2" color="red">Progress From:</font><font size="2"> $startDisplay </font><font size="2" color="red">To: </font><font size="2">$finishDisplay</font></div>

												</td>
												<td nowrap width="25%">
													<div align="center">
														<b><font size="2">GPA: </font></b><font size="2">$periodgpa </font><b><font size="2"> |  Overall GPA: </font></b><font size="2">$overallgpa</font></div>
												</td>
											</tr>

										</table>
									</div>
									<div class="noteclassic" align="left">$content
										<table width="100%" border="0" cellspacing="2" cellpadding="2">
											<tr>
												<td width="20%"></td>
											</tr>
										</table>

									</div>
									<font size="4"></font><font size="4"></font>
									<div align="center">
										<table width="100%" border="1">
											<tbody>
												<tr>
													<td colspan="7" bgcolor="#87cefa">
														<div align="center">
															<b>Core &amp; Foundation Area Courses</b></div>

													</td>
												</tr>
												<tr>
													<td bgcolor="#ccccff">
														<div class="tablehead1">
															<div align="center">
																<b><a href="(EmptyReference!)">Class Title</a></b></div>
														</div>

													</td>
													<td nowrap bgcolor="#ccccff" width="3%">
														<div class="tablehead1">
															<div align="center">
																<b><a href="(EmptyReference!)">Level</a></b></div>
														</div>
													</td>
													<td nowrap bgcolor="#ccccff" width="4%">

														<div class="tablehead1">
															<div align="center">
																<b><a href="(EmptyReference!)">Grade</a></b></div>
														</div>
													</td>
													<td nowrap bgcolor="#ccccff" width="6%">
														<div align="center">
															<b><a href="(EmptyReference!)">Completed</a></b></div>

													</td>
													<td nowrap bgcolor="#ccccff">
														<div class="tablehead1">
															<div align="center">
																<b><a href="(EmptyReference!)">Effort / QPI</a></b></div>
														</div>
													</td>
													<td nowrap bgcolor="#ccccff" width="7%">

														<div align="center">
															<b><a href="(EmptyReference!)">Progress</a></b></div>
													</td>
													<td bgcolor="#ccccff">
														<div class="tablehead1">
															<div align="center">
																<b>Comments </b></div>
														</div>

													</td>
												</tr>
												$class
												<tr>
													<td colspan="7">
														<table width="100%" border="1" cellspacing="2" cellpadding="0">
															<tr>
																<td>
																	<div align="center">
																		<font size="2"><b><u>BSSD Standards Progress Descriptors</u></b></font></div>

																</td>
																<td nowrap>
																	<div align="center">
																		<font size="2"><b><u>BSSD Secondary Level Grading &amp; GPA Values</u></b></font></div>
																</td>
																<td>
																	<div align="center">

																		<font size="2"><b><u>BSSD Effort / Quality Peformance Indicators (QPI)</u></b></font></div>
																</td>
															</tr>
															<tr>
																<td>
																	<div align="center">
																		<img src="http://dart.bssd.org/images/bssd_standards_grades.gif" alt="" height="189" width="341" border="0"></div>
																</td>

																<td>
																	<div align="center">
																		$gradesetup
																	</div>
																</td>
																<td>
																	<div align="center">
																		<img src="http://dart.bssd.org/images/bssd_qpi_scale_sm.gif" alt="" height="188" width="398" align="middle" border="0"></div>
																</td>
															</tr>

														</table>
													</td>
												</tr>
												<tr>
													<td colspan="7" bgcolor="#87cefa">
														<div align="center">
															<b>Electives &amp; Other Courses for Credit</b></div>

													</td>
												</tr>
												<tr>
													<td bgcolor="#ccccff">
														<div align="center">
															<b><a href="(EmptyReference!)">Class Title</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff" width="3%">

														<div align="center">
															<b><a href="(EmptyReference!)">Level</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff" width="4%">
														<div align="center">
															<b><a href="(EmptyReference!)">Grade</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff" width="6%">

														<div align="center">
															<b><a href="(EmptyReference!)">Completed</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff">
														<div align="center">
															<b><a href="(EmptyReference!)">Effort / QPI</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff" width="7%">

														<div align="center">
															<b><a href="(EmptyReference!)">Progress</a></b></div>
													</td>
													<td bgcolor="#ccccff">
														<div align="center">
															</div>
													</td>
												</tr>

												$electives
											</tbody>
										</table>
									</div>
								</td>
							</tr>

						</table>
					</div>
				</td>
			</tr>
		</table>
	</body>

</html>
