<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html>

	<head>
		<meta http-equiv="content-type" content="text/html;charset=iso-8859-1">
		<meta name="generator" content="Adobe GoLive">
		<title>Current Progress Report</title>
		<link rel="stylesheet" href="https://dart.bssd.org/dart_test.css" type="text/css">
	</head>

	<body bgcolor="#ffffff">
		<table border="0" cellpadding="0" cellspacing="0" background="(EmptyReference!)">
			<tr>
				<td valign="top" width="100%">
					<div align="center">
						<table width="100%" border="0" cellspacing="2" cellpadding="0">
							<tr>
								<td>

									<div align="center">
										<table width="75%" border="1" cellspacing="2" cellpadding="0">
											<tr>
												<td width="25%">
													<div align="center">
														<img src="https://dart.bssd.org/images/SchoolLogos/702602.gif" alt="" border="0"></div>
												</td>
												<td nowrap width="50%">
													<div align="center">

														<font size="4" color="black">Unalakleet Schools<br>
															Mia N Concilus</font><font size="4"><br>
															<br>
														</font><b><font size="2">Attendance: </font></b><font size="2">Present 47.0 <b>|</b> Absent 1.5 | Rate 96.5% </font><b><font size="2"><br>
																AK Student ID: </font></b><font size="2">83720<br>

															<b>Date Generated:</b> 12/15/10</font><font size="4"></font></div>
												</td>
												<td nowrap width="25%">
													<div align="center">
														<img src="https://dart.bssd.org/images/student/Concilus,%20Mia.JPG" alt="Mia Concilus - Unalakleet Schools" height="105" width="95" border="0"></div>
												</td>
											</tr>

											<tr>
												<td nowrap width="25%">
													<div align="center">
														<font size="2"><b>Enrolled: </b>2001-02:Q1</font></div>
												</td>
												<td nowrap width="50%">
													<div align="center">
														<font size="2" color="red">Progress From:</font><font size="2"> 2010-11:Q1 </font><font size="2" color="red">To: </font><font size="2">In Progress</font></div>

												</td>
												<td nowrap width="25%">
													<div align="center">
														<b><font size="2">GPA: </font></b><font size="2">3.857 </font><b><font size="2"> |  Overall GPA: </font></b><font size="2">3.634</font></div>
												</td>
											</tr>

										</table>
									</div>
									<div class="noteclassic" align="left">Thanks for a wonderful school year! There are lots of great memories to look back upon and smile about. Thanks again to parents who supported their chlidren throughout the school year and made sure they did their homework, studied for tests, and had good attendance. Your hard work helps them be successful. On behalf of the Unalakleet's Schools staff, we wish everyone a safe and relaxing summer break. See you back in school on August 23rd, 2010.<br>
										-Ben Howard 5/2010
										<table width="100%" border="0" cellspacing="2" cellpadding="2">
											<tr>
												<td width="20%"></td>
											</tr>
										</table>

									</div>
									<font size="4"></font><font size="4"></font>
									<div align="center">
										<table width="100%" border="1">
											<tbody>
												<tr>
													<td colspan="7" bgcolor="#87cefa">
														<div align="center">
															<b>Core &amp; Foundation Area Courses</b></div>

													</td>
												</tr>
												<tr>
													<td bgcolor="#ccccff">
														<div class="tablehead1">
															<div align="center">
																<b><a href="(EmptyReference!)">Class Title</a></b></div>
														</div>

													</td>
													<td nowrap bgcolor="#ccccff" width="3%">
														<div class="tablehead1">
															<div align="center">
																<b><a href="(EmptyReference!)">Level</a></b></div>
														</div>
													</td>
													<td nowrap bgcolor="#ccccff" width="4%">

														<div class="tablehead1">
															<div align="center">
																<b><a href="(EmptyReference!)">Grade</a></b></div>
														</div>
													</td>
													<td nowrap bgcolor="#ccccff" width="6%">
														<div align="center">
															<b><a href="(EmptyReference!)">Completed</a></b></div>

													</td>
													<td nowrap bgcolor="#ccccff">
														<div class="tablehead1">
															<div align="center">
																<b><a href="(EmptyReference!)">Effort / QPI</a></b></div>
														</div>
													</td>
													<td nowrap bgcolor="#ccccff" width="7%">

														<div align="center">
															<b><a href="(EmptyReference!)">Progress</a></b></div>
													</td>
													<td bgcolor="#ccccff">
														<div class="tablehead1">
															<div align="center">
																<b>Comments </b></div>
														</div>

													</td>
												</tr>
												<tr>
													<td><b>Cultural Literacy</b></td>
													<td nowrap width="3%">
														<div align="center">
															<b>CA 7</b></div>
													</td>

													<td nowrap width="4%">
														<div align="center">
															<font color="#cc0000"><b>83%  B</b></font></div>
													</td>
													<td nowrap width="6%">
														<div align="center">
															<b>In Progress</b></div>
													</td>

													<td nowrap>
														<div align="center">
															<b>Acceptable</b></div>
													</td>
													<td nowrap width="7%">
														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>
													</td>

													<td>
														<div align="left">
															Nulla odio nostrud, luptatum nostrud at tation in minim hendrerit vel ullamcorper eros dolor at suscipit ut. Woodruff  10/15</div>
													</td>
												</tr>
												<tr>
													<td><b>Career Planning</b></td>
													<td width="3%">

														<div align="center">
															<b>CS 7</b></div>
													</td>
													<td width="4%">
														<div align="center">
															<font color="#cc0000"><b>92%  A- </b></font></div>
													</td>
													<td width="6%">

														<div align="center">
															<b>In Progress</b></div>
													</td>
													<td>
														<div align="center">
															<b>Exemplary</b></div>
													</td>
													<td width="7%">

														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>
													</td>
													<td>
														<div align="left">
																(not instructed) Woodruff 12/15</div>
													</td>
												</tr>

												<tr>
													<td><b>Advanced Life Skills</b></td>
													<td nowrap width="3%">
														<div align="center">
															<b>LS 6</b></div>
													</td>
													<td nowrap width="4%">
														<div align="center">

															<b>N/A</b></div>
													</td>
													<td nowrap width="6%">
														<div align="center">
															<b>In Progress</b></div>
													</td>
													<td nowrap>
														<div align="center">

															<b>Not Instructed</b></div>
													</td>
													<td nowrap width="7%">
														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>
													</td>
													<td>
														<div align="left">

															Esse vero molestie ut dignissim enim lorem in molestie ut, feugait at dignissim crisare. </div>
													</td>
												</tr>
												<tr>
													<td><b>Algebra II</b></td>
													<td nowrap width="3%">
														<div align="center">
															<b>MA 11</b></div>

													</td>
													<td nowrap width="4%">
														<div align="center">
															<font color="#cc0000"><b>96% A</b></font></div>
													</td>
													<td nowrap width="6%">
														<div align="center">
															<b>In Progress</b></div>

													</td>
													<td nowrap>
														<div align="center">
															<b>Exemplary</b></div>
													</td>
													<td nowrap width="7%">
														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>

													</td>
													<td>
														<div align="left">
															Mia will complete Algebra 2 in December and start Trigonometry next spring. Excellent student. Woodruff 12/15/10</div>
													</td>
												</tr>
												<tr>
													<td><b>College Prep Reading</b></td>

													<td nowrap width="3%">
														<div align="center">
															<b>RE 9</b></div>
													</td>
													<td nowrap width="4%">
														<div align="center">
															<font color="#cc0000"><b>91% A-</b></font></div>
													</td>

													<td nowrap width="6%">
														<div align="center">
															<b>In Progress</b></div>
													</td>
													<td nowrap>
														<div align="center">
															<b>Exemplary</b></div>
													</td>

													<td nowrap width="7%">
														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>
													</td>
													<td>
														<div align="left">
															Mia is doing well in RE. She is developing her skills as an upper level reader and working towards A's in many of her standards. Keep up the great work. A Taylor-Brown 12/10</div>
													</td>

												</tr>
												<tr>
													<td><b>Life Science</b></td>
													<td nowrap width="3%">
														<div align="center">
															<b>SC 7L</b></div>
													</td>
													<td nowrap width="4%">

														<div align="center">
															<b>N/A</b></div>
													</td>
													<td nowrap width="6%">
														<div align="center">
															<b>In Progress</b></div>
													</td>
													<td nowrap>

														<div align="center">
															<b>Not Instructed</b></div>
													</td>
													<td nowrap width="7%">
														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>
													</td>
													<td>

														<div align="left">
																Mia's Science for 2009-10 was a university level course. She earned an A for a 4-credit Physics class with lab intensives from University of Alaska Fairbanks. This should meet the requirements of Physics in high school for college admissions, and for BSSD credit if a Physics level is added in future years. Good job! PVink 5/19/10</div>
													</td>
												</tr>
												<tr>
													<td><b>Social Studies</b></td>
													<td nowrap width="3%">
														<div align="center">

															<b>SS 9A</b></div>
													</td>
													<td nowrap width="4%">
														<div align="center">
															<b>N/A</b></div>
													</td>
													<td nowrap width="6%">
														<div align="center">

															<b>In Progress</b></div>
													</td>
													<td nowrap>
														<div align="center">
															<b>Not Instructed</b></div>
													</td>
													<td nowrap width="7%">
														<div align="center">

															<font color="#228b22"><b>On Track!</b></font></div>
													</td>
													<td>
														<div align="left">
																Not instructed. Dean 9/21/09 Mia's Social Studies for this year was a 3-credit Anthropology course via Harvard University. Although it is listed as an elective below, it was her Social Studies course for 2009-10. PVink 5/19/10</div>
													</td>
												</tr>
												<tr>

													<td><b>Advanced Technology Application</b></td>
													<td nowrap width="3%">
														<div align="center">
															<b>TE 7</b></div>
													</td>
													<td nowrap width="4%">
														<div align="center">
															<font color="#cc0000"><b>87% B+</b></font></div>

													</td>
													<td nowrap width="6%">
														<div align="center">
															<b>In Progress</b></div>
													</td>
													<td nowrap>
														<div align="center">
															<b>Disengaged</b></div>

													</td>
													<td nowrap width="7%">
														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>
													</td>
													<td>
														<div align="left">
															Veniam augue, in veniam adipiscing facilisi, duis facilisis ipsum, vulputate ut diam in aliquam ad luptatum sit et accumsan. </div>

													</td>
												</tr>
												<tr>
													<td colspan="7">
														<table width="100%" border="1" cellspacing="2" cellpadding="0">
															<tr>
																<td>
																	<div align="center">
																		<font size="2"><b><u>BSSD Standards Progress Descriptors</u></b></font></div>

																</td>
																<td nowrap>
																	<div align="center">
																		<font size="2"><b><u>BSSD Secondary Level Grading &amp; GPA Values</u></b></font></div>
																</td>
																<td>
																	<div align="center">

																		<font size="2"><b><u>BSSD Effort / Quality Peformance Indicators (QPI)</u></b></font></div>
																</td>
															</tr>
															<tr>
																<td>
																	<div align="center">
																		<img src="http://dart.bssd.org/images/bssd_standards_grades.gif" alt="" height="189" width="341" border="0"></div>
																</td>

																<td>
																	<div align="center">
																		<img src="http://dart.bssd.org/images/bssd_grading_scale.gif" alt="" height="178" width="249" align="middle" border="0"></div>
																</td>
																<td>
																	<div align="center">
																		<img src="http://dart.bssd.org/images/bssd_qpi_scale_sm.gif" alt="" height="188" width="398" align="middle" border="0"></div>
																</td>
															</tr>

														</table>
													</td>
												</tr>
												<tr>
													<td colspan="7" bgcolor="#87cefa">
														<div align="center">
															<b>Electives &amp; Other Courses for Credit</b></div>

													</td>
												</tr>
												<tr>
													<td bgcolor="#ccccff">
														<div align="center">
															<b><a href="(EmptyReference!)">Class Title</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff" width="3%">

														<div align="center">
															<b><a href="(EmptyReference!)">Level</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff" width="4%">
														<div align="center">
															<b><a href="(EmptyReference!)">Grade</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff" width="6%">

														<div align="center">
															<b><a href="(EmptyReference!)">Completed</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff">
														<div align="center">
															<b><a href="(EmptyReference!)">Effort / QPI</a></b></div>
													</td>
													<td nowrap bgcolor="#ccccff" width="7%">

														<div align="center">
															<b><a href="(EmptyReference!)">Progress</a></b></div>
													</td>
													<td bgcolor="#ccccff">
														<div align="center">
															</div>
													</td>
												</tr>

												<tr>
													<td><b>History of Art</b></td>
													<td nowrap width="3%">
														<div align="center">
															<b>AT 11</b></div>
													</td>
													<td nowrap width="4%">
														<div align="center">

															<font color="#cc0000"><b>89% B+</b></font></div>
													</td>
													<td nowrap width="6%">
														<div align="center">
															<b>In Progress</b></div>
													</td>
													<td nowrap>
														<div align="center">

															<b>Acceptable</b></div>
													</td>
													<td nowrap width="7%">
														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>
													</td>
													<td>Ullamcorper dolor, ipsum iusto accumsan. Eum ad blandit duis blandit esse veniam wisi dolore iriuredolor luptatum. Eum et ipsum, ex dolor aliquip adipiscing consequat praesent augue esse</td>

												</tr>
												<tr>
													<td><b>Korean I</b></td>
													<td nowrap width="3%">
														<div align="center">
															<b>LA 1</b></div>
													</td>
													<td nowrap width="4%">

														<div align="center">
															<font color="#cc0000"><b>94% A</b></font></div>
													</td>
													<td nowrap width="6%">
														<div align="center">
															<b>In Progress</b></div>
													</td>
													<td nowrap>

														<div align="center">
															<b>Acceptable</b></div>
													</td>
													<td nowrap width="7%">
														<div align="center">
															<font color="#228b22"><b>On Track!</b></font></div>
													</td>
													<td>

														<div align="left">Mia has done roughly 3/4 of the requirements for Korean 1 second semester from Yonsei University in Seoul, Korea by distance. Due to several weeks delay in getting the technology working, she was unable to finish, but expects to do so in September. This was challenging without a local native speaker! PVink 5/19/10</div>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</td>
							</tr>

						</table>
					</div>
				</td>
			</tr>
		</table>
	</body>

</html>