<?php

// location of root url
   $rootURL = "http://192.168.25.8/dart";
   $imageURL = $rootURL . "/images/";
   $logoURL = $rootURL . "/images/SchoolLogos/";
   $pictureURL = $rootURL . "/images/student/" ;
   $pictDIR = "htdocs/dart/images/student/";
//   $exportDIR = "htdocs/dart/exp/";
   $exportDIR = "";

// Database inforamtion
   $dbuser = "dartdb"; //   $dbuser = "root";
   $dbpassword = "wMUu29";  // $dbpassword = "vizmotion";
   $dbname = "dartdb_dartdb";
   $dbhose = "localhost";

?>
