<?php
// ==================================================================
//  Author: Robert Joseph (dart@vizmotion.com)
//	 Web: http://wiki.bssd.org/index.php/DART_System
// ==================================================================


$body = "
<div class=\"notetip\">
Welcome to the BSSD Special Education Module.
</div>
<table align=center border=1>
	<tr>
		<td>
			<a href=index.php?module=sped&cmd=spedlist>Special Education List</a>
		</td>		
	</tr>
</table>";

include_once ("template.inc");


?>

